export * from './employee-list-controller/employee-list-controller.component';
export * from './add-employee-controller/add-employee-controller.component';
export * from './personal-profile-controller/personal-profile-controller.component';
export * from './company-profile-controller/company-profile-controller.component';
export * from './document-controller/document-controller.component';
export * from './income-controller/income-controller.component';
export * from './time-leave-controller/time-leave-controller.component';
export * from './employee-controller/employee-controller.component';
export * from './advance-payment-controller/advance-payment-controller.component';
